version: "3.7"
services:
  php_app:
    # debian 12.1 (slim) + apache 2.4.57 + php 8.2.9
    image: php:8.2.9-apache-bookworm
    container_name: php_app
    restart: unless-stopped
    tty: true
    networks:
      - internal-network
    ports:
      - "8880:80"
    volumes:
      - ./httpd.conf:/etc/apache2/apache2.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./htdocs:/var/www/html
      - ./logs:/var/log/apache2
    depends_on:
      - maria_db
      - redis_cache

  node_app:
    # debian 12.1 (slim) + node 18.17 + npm 9.6.7
    image: node:18.17.1-bookworm-slim
    container_name: node_app
    restart: unless-stopped
    tty: true
    networks:
      - internal-network
    ports:
      - "8888:80"
    volumes:
      - ./node:/home/node
      - ./logs:/var/log
    depends_on:
      - maria_db
      - redis_cache

  maria_db:
    # ubuntu 22.04 + mariadb 11.1.2
    image: mariadb:11.1.2-jammy
    container_name: maria_db
    restart: unless-stopped
    tty: true
    networks:
      - internal-network
    ports:
      - "3307:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_USER: player
      MYSQL_PASSWORD: player-password
      MYSQL_DATABASE: playground

  redis_cache:
    # debian 12.1 (slim) + redis 7.2.0
    image: redis:7.2.0-bookworm
    container_name: redis_cache
    restart: unless-stopped
    tty: true
    networks:
      - internal-network
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

networks:
  internal-network:
    driver: bridge
